/**
 * Popular cities database for autocomplete
 */
const POPULAR_CITIES = [
    // Asia
    { name: "Kathmandu", country: "Nepal", region: "Asia" },
    { name: "Karachi", country: "Pakistan", region: "Asia" },
    { name: "Kabul", country: "Afghanistan", region: "Asia" },
    { name: "Tokyo", country: "Japan", region: "Asia" },
    { name: "Delhi", country: "India", region: "Asia" },
    { name: "Mumbai", country: "India", region: "Asia" },
    { name: "Bangalore", country: "India", region: "Asia" },
    { name: "Kolkata", country: "India", region: "Asia" },
    { name: "Chennai", country: "India", region: "Asia" },
    { name: "Shanghai", country: "China", region: "Asia" },
    { name: "Beijing", country: "China", region: "Asia" },
    { name: "Hong Kong", country: "Hong Kong", region: "Asia" },
    { name: "Singapore", country: "Singapore", region: "Asia" },
    { name: "Seoul", country: "South Korea", region: "Asia" },
    { name: "Bangkok", country: "Thailand", region: "Asia" },
    { name: "Manila", country: "Philippines", region: "Asia" },
    { name: "Jakarta", country: "Indonesia", region: "Asia" },
    { name: "Kuala Lumpur", country: "Malaysia", region: "Asia" },
    { name: "Dubai", country: "UAE", region: "Asia" },
    { name: "Abu Dhabi", country: "UAE", region: "Asia" },
    { name: "Riyadh", country: "Saudi Arabia", region: "Asia" },
    { name: "Tel Aviv", country: "Israel", region: "Asia" },
    { name: "Istanbul", country: "Turkey", region: "Asia" },
    { name: "Dhaka", country: "Bangladesh", region: "Asia" },
    
    // Europe
    { name: "London", country: "United Kingdom", region: "Europe" },
    { name: "Paris", country: "France", region: "Europe" },
    { name: "Berlin", country: "Germany", region: "Europe" },
    { name: "Madrid", country: "Spain", region: "Europe" },
    { name: "Rome", country: "Italy", region: "Europe" },
    { name: "Amsterdam", country: "Netherlands", region: "Europe" },
    { name: "Brussels", country: "Belgium", region: "Europe" },
    { name: "Vienna", country: "Austria", region: "Europe" },
    { name: "Prague", country: "Czech Republic", region: "Europe" },
    { name: "Warsaw", country: "Poland", region: "Europe" },
    { name: "Budapest", country: "Hungary", region: "Europe" },
    { name: "Athens", country: "Greece", region: "Europe" },
    { name: "Lisbon", country: "Portugal", region: "Europe" },
    { name: "Stockholm", country: "Sweden", region: "Europe" },
    { name: "Copenhagen", country: "Denmark", region: "Europe" },
    { name: "Oslo", country: "Norway", region: "Europe" },
    { name: "Helsinki", country: "Finland", region: "Europe" },
    { name: "Moscow", country: "Russia", region: "Europe" },
    { name: "Zurich", country: "Switzerland", region: "Europe" },
    
    // North America
    { name: "New York", country: "USA", region: "North America" },
    { name: "Los Angeles", country: "USA", region: "North America" },
    { name: "Chicago", country: "USA", region: "North America" },
    { name: "Houston", country: "USA", region: "North America" },
    { name: "Phoenix", country: "USA", region: "North America" },
    { name: "Philadelphia", country: "USA", region: "North America" },
    { name: "San Antonio", country: "USA", region: "North America" },
    { name: "San Diego", country: "USA", region: "North America" },
    { name: "Dallas", country: "USA", region: "North America" },
    { name: "San Jose", country: "USA", region: "North America" },
    { name: "Austin", country: "USA", region: "North America" },
    { name: "San Francisco", country: "USA", region: "North America" },
    { name: "Seattle", country: "USA", region: "North America" },
    { name: "Miami", country: "USA", region: "North America" },
    { name: "Boston", country: "USA", region: "North America" },
    { name: "Las Vegas", country: "USA", region: "North America" },
    { name: "Washington", country: "USA", region: "North America" },
    { name: "Toronto", country: "Canada", region: "North America" },
    { name: "Vancouver", country: "Canada", region: "North America" },
    { name: "Montreal", country: "Canada", region: "North America" },
    { name: "Mexico City", country: "Mexico", region: "North America" },
    
    // South America
    { name: "São Paulo", country: "Brazil", region: "South America" },
    { name: "Rio de Janeiro", country: "Brazil", region: "South America" },
    { name: "Buenos Aires", country: "Argentina", region: "South America" },
    { name: "Lima", country: "Peru", region: "South America" },
    { name: "Bogotá", country: "Colombia", region: "South America" },
    { name: "Santiago", country: "Chile", region: "South America" },
    { name: "Caracas", country: "Venezuela", region: "South America" },
    
    // Africa
    { name: "Cairo", country: "Egypt", region: "Africa" },
    { name: "Lagos", country: "Nigeria", region: "Africa" },
    { name: "Johannesburg", country: "South Africa", region: "Africa" },
    { name: "Cape Town", country: "South Africa", region: "Africa" },
    { name: "Nairobi", country: "Kenya", region: "Africa" },
    { name: "Casablanca", country: "Morocco", region: "Africa" },
    { name: "Accra", country: "Ghana", region: "Africa" },
    
    // Oceania
    { name: "Sydney", country: "Australia", region: "Oceania" },
    { name: "Melbourne", country: "Australia", region: "Oceania" },
    { name: "Brisbane", country: "Australia", region: "Oceania" },
    { name: "Perth", country: "Australia", region: "Oceania" },
    { name: "Auckland", country: "New Zealand", region: "Oceania" },
    { name: "Wellington", country: "New Zealand", region: "Oceania" }
];
