FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY snapshot/ ./snapshot/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "snapshot/snapshot_consumer.py"]
